config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root 'application#index'
  get 'show_products/:id', to: "application#show_products", as: 'show_products'
  resources :category, only: %i[create new delete destroy edit update patch]
  resources :product, only: %i[create new delete destroy edit update patch]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :products, dependent: :delete_all
  has_ancestry
end

app/models/product.rb
class Product < ApplicationRecord
  belongs_to :category
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  def index
    @products = Product.all
    @categories = Category.all
    render 'index'
  end

  def show_products
    @products = Product.where(:category_id => Category.find(params[:id]).subtree_ids)
    @categories = Category.all
    render 'index'
  end
end

app/controllers/category_controller.rb
class CategoryController < ApplicationController

  def create
    @category = Category.create(user_params)
    if @category.save
      redirect_to root_path
    else
      render :new
    end
  end

  def destroy
    Category.find(params[:id]).destroy
    redirect_to root_path
  end

  def new
    @category = Category.new
  end

  def edit
    @category = Category.find(params[:id])
  end

  def update
    @category = Category.find(params[:id])
    if @category.update_attributes(user_params)
      redirect_to root_path
    else
      render :edit
    end
  end

  def user_params
    params.require(:category).permit(:title, :parent_id)
  end

end

app/controllers/product_controller.rb
class ProductController < ApplicationController

  def create
    @product = Product.create(user_params)
    if @product.save
      redirect_to show_products_path(params[:product][:category_id])
    else
      render :new
    end
  end

  def destroy
    Product.find(params[:id]).destroy
    redirect_to show_products_path(params[:product][:category_id])
  end

  def new
    @product = Product.new
  end

  def edit
    @product = Product.find(params[:id])
  end

  def update
    @product = Product.find(params[:id])
    if @product.update_attributes(user_params)
      redirect_to show_products_path(params[:product][:category_id])
    end
  end

  def user_params
   @category = params[:category]
   params.require(:product).permit(:title, :manufacturer, :price, :category_id)
  end

end

app/helpers/application_helper.rb
# coding: utf-8
module ApplicationHelper

  def nested_categories(categories)
    categories.map do |category, sub_categories|
      render html: content_tag(:div, category.title, :class => "category") + cat_edit_button(category.id) + cat_delete_button(category.id) + cat_show_button(category.id) + content_tag(:div, nested_categories(sub_categories), :class => "sub_category")
    end.join.html_safe
  end

  def cat_new_button()
    content_tag(:button, link_to("+" , new_category_path), class: "plus_button app_button")
  end

  def cat_edit_button(id)
    content_tag(:button, link_to("Edit", edit_category_path(id)), class: "edit_button app_button")
  end

  def cat_delete_button(id)
    content_tag(:button, link_to("-", category_path(id), method: :delete, data: {confirm: "Вы уверены?"}), class: "minus_button app_button")
  end

  def cat_show_button(id)
    content_tag(:button, link_to("Show", show_products_path(id), method: :get), class: "show_button app_button")
  end

  def prod_new_button()
    content_tag(:button, link_to("+", new_product_path), class: "plus_button app_button")
  end

  def prod_edit_button(id)
    content_tag(:button, link_to("Edit", edit_product_path(id)), class: "edit_button app_button")
  end

  def prod_delete_button(id)
    content_tag(:button, link_to("-", product_path(id), method: :delete, data: {confirm: "Вы уверены?"}), class: "minus_button app_button")
  end

end

app/helpers/category_helper.rb
module CategoryHelper
end

app/helpers/product_helper.rb
module ProductHelper
end

app/views/application/index.html.haml
.wrapper
  .app_categories_list
    %h1.app_table_header Категории
    .app_categories_container

      = nested_categories @categories.arrange(:order => :created_at)

    .app_control_group
      = cat_new_button
  .app_products_list
    %h1.app_table_header Товары
    %table
      %tr
        %th Категория
        %th ID
        %th Название
        %th Производитель
        %th Цена
        %th Управление
      - @products.each do |product|
        %tr
          %td
            = Category.find(product.category_id).title
          %td
            = product.id
          %td
            = product.title
          %td
            = product.manufacturer
          %td
            = product.price
          %td
            = prod_edit_button(product.id)
            = prod_delete_button(product.id)
    .app_control_group
      = prod_new_button

app/views/category/_form.html.haml
= form_for @category do |f|
  %div
    = f.label :title, "Название категории:"
    %br
    = f.text_field :title
    %rb
  %div
    = f.label :parent_id, "Категория предок:"
    %br
    = f.select :parent_id, options_from_collection_for_select(Category.all, :id, :title), prompt: 'Нет'
  %br
  %div
    = f.submit

app/views/category/edit.html.haml
%h1 Изменение категории

= render 'form'

app/views/category/new.html.haml
%h1 Создание категории

= form_for @category, url: category_index_url do |f|
  %div
    = f.label :title, "Название категории:"
    %br
    = f.text_field :title
    %rb
  %div
    = f.label :parent_id, "Категория предок:"
    %br
    = f.select :parent_id, options_from_collection_for_select(Category.all, :id, :title), prompt: 'Нет'
  %br
  %div
    = f.submit

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Pbd</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/product/edit.html.haml
%h1 Изменение продукта

= form_for @product do |f|
  = f.label :title, "Название: "
  %br
  = f.text_field :title
  %br
  = f.label :manufacturer, "Производитель: "
  %br
  = f.text_field :manufacturer
  %br
  = f.label :price, "Цена: "
  %br
  = f.text_field :price
  %br
  = f.label :category_id, "Категория: "
  %br
  = f.select :category_id, options_from_collection_for_select(Category.all, "id", "title")
  %br
  %br
  = f.submit "Изменить продукт"

app/views/product/new.html.haml
%h1 Создание продукта

= form_for @product, url: product_index_url do |f|
  = f.label :title, "Название: "
  %br
  = f.text_field :title
  %br
  = f.label :manufacturer, "Производитель: "
  %br
  = f.text_field :manufacturer
  %br
  = f.label :price, "Цена: "
  %br
  = f.text_field :price
  %br
  = f.label :category_id, "Категория: "
  %br
  = f.select :category_id, options_from_collection_for_select(Category.all, "id", "title")
  %br
  = f.submit "Сохранить продукт"